[package]
name = "kademlia"
version = "0.1.0"
authors = ["solanav"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.0"

[lib]
test = true
bench = true
doc = true